### ISSUE TITLE
Kinfu output mesh disjoint

### ISSUE THREAD

**Issue by aecins** [arpg/Kangaroo#5]
I have a trouble generating a mesh from Kinect Fusion. I can generate the output mesh, however the mesh seems to be segmented into many disjoint patches. Here is a visualization of the connected components in a mesh, every component is coloured differently:
![image](https://cloud.githubusercontent.com/assets/4580832/6456600/7c59bf84-c134-11e4-916d-11bec0f06560.png)

Is there a way to fix this?

**Comment by lumark** [comment]
It seems like the input rgb image for fusion is incorrect. Looks like its some random value in the memory. Are you sure you have the correct input images?

**Comment by aecins** [comment]
I am not using RGB data for fusion. I have fused depth data only and saved the mesh to an `.stl` file using [`roo::saveMesh`](https://github.com/arpg/Kangaroo/blob/9b1e65151727a2a57a260acdfcd6f053dfa44bea/kangaroo/MarchingCubes.h#L246). To obtain the image above I have extracted the connected components of the graph formed by the edges in the mesh. The points in the cloud above are coloured according to the connected component they belong to.  As you can see there are multiple connected components that are disjoint but should be connected (for example patches on the wall).

My guess is that these patches are somehow linked to the blocks of memory storing the SDF in the GPU. On the other hand the whole SDF volume is copied to host memory [`here`](https://github.com/arpg/Kangaroo/blob/9b1e65151727a2a57a260acdfcd6f053dfa44bea/kangaroo/MarchingCubes.h#L250) before running marching cubes on it, so GPU memory partitioning should not be an issue.

**Comment by aecins** [comment]
I figured out what the problem is. [Marching cubes](https://github.com/arpg/Kangaroo/blob/master/kangaroo/MarchingCubes.h#L225) outputs a set of connected polygons for each of the voxels in the TSDF. However the polygons for adjacent voxels are not connected i.e. none of the vertices are "reused" between two adjacent voxel polygons.  Instead the polygon vertex coordinates at the boundary between two voxels are very close to each other, but still are distinct vertices. In order to connect the adjacent voxel polygons you need to simplify the mesh by merging the vertices that are closer than some threshold to each other. [`vtkCleanPolyData`](http://www.vtk.org/doc/nightly/html/classvtkCleanPolyData.html) will do this for you.

**Comment by lumark** [comment]
Hi Aleksandrs,

I never had this issue before. Glad that you fix it and thanks for pointing
this out.

Best,
Lu
