### ISSUE TITLE
Kinect fusion mesh artifacts

### ISSUE THREAD

**Issue by aecins** [arpg/Kangaroo#6]
I am trying to scan an tabletop scene using KinectFusion. Everything works fine except for weird artifacts that appear at depth discontinuities. The surfaces at depth discontinuities are "extended" in the direction of the optical axis of the camera. Here is an example:

Front:
![front](https://cloud.githubusercontent.com/assets/4580832/6767438/44f747f6-d006-11e4-8f24-aec44e54faa4.png)

Side:
![side1](https://cloud.githubusercontent.com/assets/4580832/6767448/9c69858a-d006-11e4-8f8d-9cfab38a9238.png)
![side2](https://cloud.githubusercontent.com/assets/4580832/6767450/9e9dff02-d006-11e4-8a00-ecf89bb11646.png)

The maximum allowed angle between the viewing ray and surface normal is set to 75 degrees. I tried reducing that but then very few scene points are captured. Is there a way to solve the issue without sacrificing the coverage of the scene?

**Comment by Algomorph** [comment]
Hey, Alex. This may or may not be related in part to [this HAL issue](https://github.com/arpg/HAL/issues/82). If you recall from the noise patterns, they occur a lot around the edges. Perhaps the newer freenect2 will be able to reduce the noise.

**Comment by crheckman** [comment]
@aecins have you tried the newer freenect2 to see if this solves the problem?

**Comment by aecins** [comment]
I have finally got back to this project and figured out what was the issue. The reason I was getting these artifacts was that my calibration was not accurate enough. I have recalibrated my Kinect and am getting nice reconstructions now.

**Comment by crheckman** [comment]
Great; thanks!
