### ISSUE TITLE
MarchingCubes.h compilation error

### ISSUE THREAD

**Issue by Algomorph** [arpg/Kangaroo#7]
We're getting this compilation error consistently across three Ubuntu machines using gcc.
```MarchingCubes.h:64:42: error: there are no arguments to ‘isfinite’ that depend on a template parameter, so a declaration of ‘isfinite’ must be available [-fpermissive]```

In the source, it ther is a check whether compiler is MSVC. If so, it uses ```std::isinfinite```. Simply changing the clause to ``` __GNUC__``` *or* ```MSVC``` seems to resolve the compilation problem.

**Comment by Algomorph** [comment]
Anyone?

**Comment by crheckman** [comment]
If you could submit a PR with the change that would be the best way to resolve this issue; then our Jenkins server will give it a test and the relevant developers will merge the PR after they've looked it over.

Thanks for bringing this up :+1:
